version: '3'

services:
################################
#### SETUP SERVER CONTAINER ####
################################
    server:
        build:
            context: .\server\
        expose: 
            - "8080"
        # environment: 
        #     - API_HOST: http://localhost/8080
        #     - APP_SERVER_PORT: "8080"
        ports:
            - "8080:8080"
        # volumes:
        #     - ./server/src:/srv/app/server/src
        #     - ./server/seed/:/srv/app/server/seed
        command: npm run start

################################
#### SETUP CLIENT CONTAINER ####
################################
    client:
        build: 
            context: .\client\
        # environment: 
        #     - VUE_APP_PORT: "8081"
        expose: 
            - "8081"
        ports:
            - "8081:8081"
        # volumes:
        #     - ./client/src:/srv/app/client/src
        #     - ./client/public/:/srv/app/client/public
        links:
            - server
        command: npm run dev